export type CampSheetUpdate = {
  name?: string;
  priceFrom?: number;
  priceNote: string;
  capacity?: number;
  tags: string[];
  highlights: string[];
  activities: string[];
  stayOptions: string[];
  rules: string[];
};

export const campSheetUpdates: Record<string, CampSheetUpdate> = {
  'villa-altagracia': {
    name: 'Villa Altagracia',
    priceFrom: 750,
    priceNote: 'Desde RD$750 por noche',
    capacity: 200,
    tags: ['Bosque', 'Rio', 'Cascada', 'Piscina'],
    highlights: ['Camping y cabana ecologica', 'Balneario con rio, cascada y piscina', 'No requiere vehiculo 4x4', 'No cuenta con restaurante'],
    activities: ['Rio', 'Cascada', 'Piscina', 'Camping'],
    stayOptions: ['Camping', 'Cabana ecologica'],
    rules: ['No requiere vehiculo 4x4', 'Confirmar disponibilidad y condiciones antes de reservar'],
  },
  monsenor: {
    name: 'Monseñor',
    priceFrom: 1000,
    priceNote: 'Desde RD$1,000 por noche',
    capacity: 50,
    tags: ['Bosque', 'Presa', 'Restaurante'],
    highlights: ['Camping en bosque', 'Balneario tipo presa', 'Cuenta con comida/restaurante', 'No requiere vehiculo 4x4'],
    activities: ['Presa', 'Camping', 'Naturaleza'],
    stayOptions: ['Camping'],
    rules: ['No requiere vehiculo 4x4', 'Confirmar condiciones actualizadas antes de reservar'],
  },
  bonao: {
    priceFrom: 700,
    priceNote: 'Desde RD$700 por noche; no incluye equipos',
    capacity: 50,
    tags: ['Montana', 'Rio', 'Cascada'],
    highlights: ['Camping en montana', 'Balneario con rio y cascada', 'No requiere vehiculo 4x4', 'No cuenta con restaurante'],
    activities: ['Rio', 'Cascada', 'Senderismo', 'Camping'],
    stayOptions: ['Camping no incluye equipos'],
    rules: ['No requiere vehiculo 4x4', 'Llevar alimentos y equipos si aplica'],
  },
  ocoa: {
    priceFrom: 800,
    priceNote: 'Desde RD$800 por noche',
    capacity: 50,
    tags: ['Montana', 'Rio', 'Cascada'],
    highlights: ['Camping en montana', 'Balneario con rio y cascada', 'No requiere vehiculo 4x4', 'No cuenta con restaurante'],
    activities: ['Rio', 'Cascada', 'Camping', 'Naturaleza'],
    stayOptions: ['Camping'],
    rules: ['No requiere vehiculo 4x4', 'Confirmar condiciones antes de salir'],
  },
  jarabacoa: {
    priceFrom: 800,
    priceNote: 'Desde RD$800 por noche',
    capacity: 80,
    tags: ['Montana', 'Rio', 'Cascada', 'Restaurante'],
    highlights: ['Camping y tiny house', 'Cuenta con comida/restaurante', 'Balneario con rio y cascada', 'No requiere vehiculo 4x4'],
    activities: ['Rio', 'Cascada', 'Senderismo', 'Camping'],
    stayOptions: ['Camping', 'Tiny House'],
    rules: ['No requiere vehiculo 4x4', 'Confirmar disponibilidad de alojamientos'],
  },
  constanza: {
    priceFrom: 1500,
    priceNote: 'Desde RD$1,500 por noche; camping no incluye equipos',
    capacity: 100,
    tags: ['Montana', 'Clima fresco', 'Restaurante'],
    highlights: ['Camping de montana', 'Cuenta con comida/restaurante', 'No requiere vehiculo 4x4', 'Ideal para clima fresco'],
    activities: ['Camping', 'Picnic', 'Naturaleza'],
    stayOptions: ['Camping no incluye equipos'],
    rules: ['No requiere vehiculo 4x4', 'Llevar abrigo para la noche'],
  },
  'pinar-del-valle': {
    name: 'Pinar de Constanza',
    priceFrom: 1500,
    priceNote: 'Desde RD$1,500 por noche',
    capacity: 50,
    tags: ['Montana', 'Cabana ecologica', 'Restaurante'],
    highlights: ['Camping y cabana ecologica', 'Cuenta con comida/restaurante', 'No requiere vehiculo 4x4', 'Entorno de montana'],
    activities: ['Camping', 'Naturaleza', 'Descanso'],
    stayOptions: ['Camping', 'Cabana ecologica'],
    rules: ['No requiere vehiculo 4x4', 'Confirmar condiciones actualizadas'],
  },
  santiago: {
    priceFrom: 900,
    priceNote: 'Desde RD$900 por noche',
    capacity: 30,
    tags: ['Bosque', 'Presa', 'Piscina', 'Restaurante'],
    highlights: ['Camping, glamping y habitaciones', 'Cuenta con comida/restaurante', 'Balneario con presa y piscina', 'No requiere vehiculo 4x4'],
    activities: ['Presa', 'Piscina', 'Camping', 'Glamping'],
    stayOptions: ['Camping', 'Glamping', 'Habitaciones'],
    rules: ['No requiere vehiculo 4x4', 'Confirmar cupo antes de reservar'],
  },
  taiku: {
    priceFrom: 600,
    priceNote: 'Desde RD$600 por noche',
    capacity: 50,
    tags: ['Bosque', 'Rio', 'Glamping', '4x4'],
    highlights: ['Camping y glamping', 'Cuenta con comida/restaurante', 'Balneario de rio', 'Se requiere vehiculo 4x4'],
    activities: ['Rio', 'Camping', 'Glamping', 'Naturaleza'],
    stayOptions: ['Camping', 'Glamping'],
    rules: ['Se requiere vehiculo 4x4', 'Confirmar acceso antes de salir'],
  },
  montellano: {
    name: 'Montellano, Puerto Plata',
    priceFrom: 900,
    priceNote: 'Desde RD$900 por noche',
    capacity: 40,
    tags: ['Bosque', 'Rio', 'Tiny House', 'Restaurante'],
    highlights: ['Camping, cabana ecologica y tiny house', 'Cuenta con comida/restaurante', 'Balneario de rio', 'No requiere vehiculo 4x4'],
    activities: ['Rio', 'Camping', 'Naturaleza'],
    stayOptions: ['Camping', 'Cabana ecologica', 'Tiny House'],
    rules: ['No requiere vehiculo 4x4', 'Confirmar disponibilidad de alojamiento'],
  },
  'los-cacaos': {
    name: 'Los Cacaos',
    priceFrom: 3500,
    priceNote: 'Desde RD$3,500 por noche; todo incluido',
    capacity: 90,
    tags: ['Montana', 'Rio', 'Todo incluido'],
    highlights: ['Experiencia todo incluido', 'Camping, tiny house y cabana ecologica', 'Balneario de rio', 'No requiere vehiculo 4x4'],
    activities: ['Rio', 'Camping', 'Naturaleza', 'Descanso'],
    stayOptions: ['Camping', 'Tiny House', 'Cabana ecologica'],
    rules: ['No requiere vehiculo 4x4', 'Confirmar que incluye el plan todo incluido'],
  },
  'san-cristobal': {
    priceFrom: 1000,
    priceNote: 'Desde RD$1,000 por noche; en remodelacion',
    tags: ['Llano', 'Piscina', 'Todo incluido'],
    highlights: ['Camping y cabana ecologica', 'Piscina', 'Opciones todo incluido', 'Actualmente indicado como remodelando'],
    activities: ['Piscina', 'Camping', 'Relax'],
    stayOptions: ['Camping', 'Cabana ecologica'],
    rules: ['No requiere vehiculo 4x4', 'Confirmar estatus de remodelacion antes de reservar'],
  },
  azua: {
    priceFrom: 1400,
    priceNote: 'Desde RD$1,400 por noche',
    capacity: 20,
    tags: ['Llano', 'Piscina', 'Playa', '4x4'],
    highlights: ['Camping, glamping y habitacion', 'Cuenta con comida/restaurante', 'Balneario con piscina y playa', 'Se requiere vehiculo 4x4'],
    activities: ['Piscina', 'Playa', 'Camping', 'Glamping'],
    stayOptions: ['Camping', 'Glamping', 'Habitacion'],
    rules: ['Se requiere vehiculo 4x4', 'Confirmar acceso y disponibilidad antes de salir'],
  },
  'santo-domingo': {
    priceFrom: 2560,
    priceNote: 'Desde RD$2,560 por noche',
    capacity: 100,
    tags: ['Llano', 'Cenote', 'Piscina', 'Restaurante'],
    highlights: ['Camping, tiny house y cabana ecologica', 'Cuenta con comida/restaurante', 'Balneario con cenote y piscina', 'No requiere vehiculo 4x4'],
    activities: ['Cenote', 'Piscina', 'Camping'],
    stayOptions: ['Camping', 'Tiny House', 'Cabana ecologica'],
    rules: ['No requiere vehiculo 4x4', 'Confirmar disponibilidad antes de reservar'],
  },
  comatillo: {
    priceFrom: 2200,
    priceNote: 'Desde RD$2,200 por noche; opciones todo incluido',
    capacity: 500,
    tags: ['Selva', 'Rio', 'Piscina', 'Todo incluido'],
    highlights: ['Camping y cabana ecologica', 'Opciones todo incluido', 'Balneario con rio y piscina', 'No requiere vehiculo 4x4'],
    activities: ['Rio', 'Piscina', 'Camping', 'Naturaleza'],
    stayOptions: ['Camping', 'Cabana ecologica'],
    rules: ['No requiere vehiculo 4x4', 'Confirmar condiciones del plan todo incluido'],
  },
  'hato-mayor': {
    priceFrom: 700,
    priceNote: 'Desde RD$700 por noche',
    capacity: 500,
    tags: ['Selva', 'Rio', 'Cascada', 'Restaurante'],
    highlights: ['Camping en selva', 'Cuenta con comida/restaurante', 'Balneario con rio y cascada', 'No requiere vehiculo 4x4'],
    activities: ['Rio', 'Cascada', 'Camping', 'Naturaleza'],
    stayOptions: ['Camping'],
    rules: ['No requiere vehiculo 4x4', 'Confirmar disponibilidad antes de reservar'],
  },
  lavacama: {
    name: 'Playa Lavacama, Punta Cana',
    priceFrom: 1800,
    priceNote: 'Desde RD$1,800 por noche',
    capacity: 50,
    tags: ['Playa', 'Bubble Glamping', 'Restaurante'],
    highlights: ['Camping, bubble glamping y cabana ecologica', 'Cuenta con comida/restaurante', 'Balneario de playa', 'No requiere vehiculo 4x4'],
    activities: ['Playa', 'Camping', 'Glamping', 'Relax'],
    stayOptions: ['Camping', 'Bubble Glamping', 'Cabana ecologica'],
    rules: ['No requiere vehiculo 4x4', 'Confirmar disponibilidad antes de salir'],
  },
  'rincon-samana': {
    name: 'Samana, Rincon',
    priceFrom: 700,
    priceNote: 'Desde RD$700 por noche',
    capacity: 50,
    tags: ['Llano', 'Piscina', 'Cabana ecologica'],
    highlights: ['Camping y cabana ecologica', 'Balneario con piscina', 'No requiere vehiculo 4x4', 'No cuenta con restaurante'],
    activities: ['Piscina', 'Camping', 'Relax'],
    stayOptions: ['Camping', 'Cabana ecologica'],
    rules: ['No requiere vehiculo 4x4', 'Confirmar disponibilidad antes de reservar'],
  },
  'el-valle': {
    name: 'El Valle, Samana',
    priceFrom: 700,
    priceNote: 'Desde RD$700 por noche; camping no incluye equipos',
    capacity: 100,
    tags: ['Playa', 'Restaurante', 'Camping'],
    highlights: ['Camping de playa', 'Cuenta con comida/restaurante', 'Balneario de playa', 'No requiere vehiculo 4x4'],
    activities: ['Playa', 'Camping', 'Fotos', 'Relax'],
    stayOptions: ['Camping no incluye equipos'],
    rules: ['No requiere vehiculo 4x4', 'Confirmar condiciones de temporada'],
  },
};
